site_name: "My Professional Site"
site_url: "https://haricharan12.github.io/my-website/"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
  palette:
    scheme: slate
    primary: indigo
    accent: cyan
  icon:
    repo: fontawesome/brands/github
repo_url: "https://github.com/haricharan12/my-website"
repo_name: "GitHub Repo"

nav:
  - Home: index.md
  - About: about.md
  - Guides:
      - Setup: guides/setup.md
      - Usage: guides/usage.md
  - Blog:
      - "First Post": blog/post1.md
      - "Second Post": blog/post2.md
  - Contact: contact.md
